name: danger
on:
  pull_request:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@production
      - name: Use Node.js 12.x
        uses: actions/setup-node@production
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
      - name: Danger
        run: npm run danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }} 
